### PR TITLE
routes: Add cancellability middleware and cancellable param

### PR DESCRIPTION
**Pull request by smspillaz**
We'll use this later to cancel in flight requests in case of an interrupt.  https://phabricator.endlessm.com/T21897

### CODE REVIEW

**Comment by smspillaz** [comment]
```I would have expected to see some code as part of this PR that avoids reporting an error to the server in case the error is G_IO_ERROR_CANCELLED. Do we not need that?

Other than that, it looks fine, but I am mindful of the fact that without such code we may end up seeing error pages on the android app when requests are cancelled.```

I will have to do some testing here but I am pretty sure the only way a request will currently get cancelled is if the android side hangs up. In that case one probably would not see an error. I could be wrong on this though  @zoroz any thoughts?

**Comment by cosimoc** [comment]
Tagging here @zarkooroz

**Comment by cosimoc** [comment]
@smspillaz The original reason to do the cancellation was to avoid doing a lot of work when typing a lot of characters in a row for search, since the search may take longer than the time between two key presses.

**Comment by smspillaz** [comment]
> @smspillaz The original reason to do the cancellation was to avoid doing a lot of work when typing a lot of characters in a row for search, since the search may take longer than the time between two key presses.

Indeed. AIUI, the original request will be aborted when a new one gets made

**Comment by cosimoc** [comment]
We should split this PR into two parts:
- a first part that adds cancellability support to the server methods by adding cancellable parameters everywhere and adding it to the relevant messages
- a second part that actually calls `cancel()` on the cancellable when appropriate

I am not comfortable with the second piece going in without a test that no errors end up being returned to the caller in that circumstance, since I'm afraid the caller otherwise will happily show an error page.

**Comment by smspillaz** [comment]
Fair enough. I opened https://github.com/endlessm/eos-companion-app-integration/pull/108 to dig into that further

**Pull request merged**
