### PR TITLE
T21897: Cancel operations on 'request-aborted'

### PR DESCRIPTION
**Pull request by smspillaz**
https://phabricator.endlessm.com/T21897

### CODE REVIEW

**Comment by cosimoc** [comment]
@smspillaz Can you please rebase this to latest master?

**Comment by smspillaz** [comment]
per

@cosimoc 

> I am not comfortable with the second piece going in without a test that no errors end up being returned to the caller in that circumstance, since I'm afraid the caller otherwise will happily show an error page.

**Comment by zarkooroz** [comment]
> I am not comfortable with the second piece going in without a test that no errors end up being returned to the caller in that circumstance, since I'm afraid the caller otherwise will happily show an error page.

On the client side, as soon as new request is made, previous one is canceled. Canceled request responses are ignored. There should not be an error message displayed on client side.

**Comment by smspillaz** [comment]
> I am not comfortable with the second piece going in without a test that no errors end up being returned to the caller in that circumstance, since I'm afraid the caller otherwise will happily show an error page.

@cosimoc thinking about this some more, I think that we should return an error to the client (specifically, a `CANCELLED` error) in such a case. There's two scenarios to consider here:

1. Where the client has terminated the relevant connection: In this case, it does not matter what we send as the connection will no longer be connected
2. When the client is connected but cancellation occurs for some other reason: We should prefer sending an error to doing nothing. The client will be waiting on a response and that is the best we can send it.

**Comment by smspillaz** [comment]
Closing in favor of #111

**Pull request closed without merging**
